main: com.kerrishaus.ErosteyWorship.ErosteyWorship
name: ErosteyWorship
version: '1.0'
description: Gods
#load: POSTWORLD
author: kennyrkun
website: kerrishaus.com
api-version: 1.20
#prefix: Testing
#depend:
#- WorldEdit
#- Towny
#softdepend:
#- FAWE
#loadbefore:
#- Essentials
commands:
  god:
    description: Manages ErosteyWorship.
    aliases:
    - gods
    permission: erostey.god
    permission-message: Insufficient permissions. (String from config.)
    usage: Very carefully.
permissions:
  erostey.god:
    description: Allows god command
    default: op
#  test.*:
#    description: Wildcard permission
#    default: op
#    children:
#      test.foo: true